name       : ruby-winrm-fs
version    : 1.3.4
release    : 4
source     :
    - https://rubygems.org/downloads/winrm-fs-1.3.4.gem : 834cd9dd81c6a330d33bacbc70ad37a82d58224c4c72ccb6e92cad4451326e24
license    : Apache-2.0
component  : programming.ruby
summary    : RubyGem - winrm-fs
description: |
    Ruby library for file system operations via Windows Remote Management.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-erubi
    - ruby-logging
    - ruby-winrm
    - rubyzip
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
